# Tidyup 2: re-unification of tidyr and stringr

Champion: Hadley

Status: Proposal

## Motivation

-   stringr was designed before I understood how important data frames were, so multi-column results use matrices.
    This makes them hard to immediately use in other tidyverse packages.

-   To overcome this challenge, tidyr provides some functions that make it easy to split up characters into multiple variables.
    Unforunately, the tidyr and stringr function names are not well aligned:

    -   `extract()` is similar to `str_match()`
    -   `separate()` with regex is similar to `str_split_fixed()`
    -   `separate()` with numeric columns has no equivalent in stringr.
    -   `separate_rows()` is equivalent to `str_split()`

-   In order to keep dependencies light, tidyr doesn't use stringr in `separate()`, `separate_rows()`, or `extract()`.
    There are relatively few difference between PCRE and ICU regular expression engines, but you need to use a very different syntax for (e.g.) ignoring case.

-   There are some missing pieces: there are no equivalents of

## Outlined proposal

Create new families of functions in both tidyr and stringr that:

-   

## Details
